Query & Update animals table
eric2umeh/vet_clinic_postgresql pull request #2
Opened 2023-03-28 18:07 UTC by eric2umeh

In this PR,

- [x] Use database transactions.
- [x] Modify and delete data in SQL by;
- Add SQL to modify the "animals" table with a new species column in `schema.sql`.
- Add SQL to insert more data into the "animals" table in `data.sql`.
- [x] Prepare complex queries that answer analytical questions.
- Add queries using transactions & add queries using aggregate functions in `queries.sql`.
- [x] Follow correct Gitflow
- [x] Check for Linters

Below are the screenshots of the results of the SQL commands used in this milestone.

1. Add a new column species to the "animals" table & insert data.
<img width="1280" alt="Screenshot 2023-03-28 at 17 46 14" src="https://user-images.githubusercontent.com/32669797/228323245-f6bcd21e-8135-4796-aee6-1c5efb9019b6.png">

- 2.1. Transaction update the animals table by setting the species column to unspecified
<img width="618" alt="Screenshot 2023-03-28 at 17 47 27" src="https://user-images.githubusercontent.com/32669797/228323277-219743de-cc0b-4d6e-8ece-65c88816e0d7.png">

- 2.2. Re-update Transactions & commit
<img width="615" alt="Screenshot 2023-03-28 at 17 48 25" src="https://user-images.githubusercontent.com/32669797/228323285-0ea498ea-4877-4a41-a88b-8284f3b62681.png">

- 2.3. Including Queries before COMMIT;
<img width="615" alt="Screenshot 2023-03-29 at 09 12 26" src="https://user-images.githubusercontent.com/32669797/228470608-7820bb5b-e3bb-419b-be26-8757b035be2f.png">

- 3. Transaction delete all records in the animals table, then roll back the transaction.
<img width="611" alt="Screenshot 2023-03-28 at 17 53 15" src="https://user-images.githubusercontent.com/32669797/228323298-81426d97-4f53-4390-ad8e-10d7c2725b1b.png">

- 4.1. CRUD transaction
<img width="597" alt="Screenshot 2023-03-28 at 18 06 39" src="https://user-images.githubusercontent.com/32669797/228323308-cc790bf8-ffb4-4fa5-84b1-b721a318657c.png">

- 4.2. Cont'd
<img width="593" alt="Screenshot 2023-03-28 at 18 06 52" src="https://user-images.githubusercontent.com/32669797/228323316-36f83c63-df11-4963-bc53-d400472dc2dc.png">

- 5.1. Query Questions
<img width="652" alt="Screenshot 2023-03-28 at 18 34 08" src="https://user-images.githubusercontent.com/32669797/228323322-4def036d-51dc-412c-8ab2-2ab5f68e6c2d.png">

- 5.2.
<img width="655" alt="Screenshot 2023-03-28 at 18 36 17" src="https://user-images.githubusercontent.com/32669797/228323325-0d919374-2115-4a0c-ad7e-947962626a6b.png">

2023-03-28 18:15 UTC, AnselemOdims requested changes
### Hi @eric2umeh , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-28 18:15 UTC, AnselemOdims commented on queries.sql
> +SELECT * FROM animals;
- [x] Please kindly include a query to verify that the change was made before committing.

2023-03-29 08:16 UTC, eric2umeh commented on queries.sql
> +SELECT * FROM animals;
Thank you @AnselemOdims ,
I have included the queries before committing.

2023-03-29 08:21 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @eric2umeh, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did well to make the change requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 14:03 UTC, merged